### ISSUE TITLE
Problem when creating new flashcard set.

### ISSUE THREAD

**Issue by whitman-colm** [HyperChicken-Interactive/flashcard#2]
Probably some shoddy logic in EditorViewController. When creating a new flashy set, it puts `example 1` in the short name box, this is a design flaw on my end because I needed a way to identify the sets. 

But, this can lead to a whole slew of problems with the `updateValuesInView` function within EditorViewController, which is run twice when the `done` button is pressed, causing the card number to go add one and maybe create a new card, (If you're on card 1, pressing the button puts you at card 2). This can be disastrous by trapping the user in the editor when creating a new cardset.

I haven't the faintest on how to fix it, but it can probably be prevented from happening in the first place by maybe creating a new member of `FlashySet`, `isUninitialized`. It could be a boolean that is set to false by default but set to true when opening the editor. Add logic in the EditorViewController's `UIViewController` subclass to clear the short name text field, set `editSet.shortname` to `""` (**NOT `NIL`. I HAVE SINNED BY USING FORCE OPTIONAL UNRAVELS. THAT. WILL. CRASH. THE. APP**), and set `editSet.isUninitialized` to `true`.

Another, nicer, but much harder way to do this is by removing "example" and trying to make an array that can be continually appended to as new cardsets are created. This will probably be the option used in the final release but for now, it's your choice.

**Comment by donovank** [comment]
How often does this error occur? I've never seen it happen.

**Comment by whitman-colm** [comment]
This occurs every time the "done" button is pressed with no cards made. See [here](http://www.giphy.com/gifs/3oriNTEQ0K8s5etnKE)

**Comment by whitman-colm** [comment]
Actually, scratch that. This bug occurs **every** time the `done` button is pressed. The value of `currentlyselectedcard` goes up by 1, and the values update accordingly. I am in the process of adding a tonne of `logdata(...)` functions to see where anything out of the ordinary happens.

**Comment by whitman-colm** [comment]
Well aren't me a dingle.

The issue was fixed. There was an incorrectly defined `Received Action` between `nextAction` in `EditorViewController.swift` and the button in the storyboard that has predefined text of *done* in the `EditorView`.
